name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Jalankan otomatis saat push ke branch main

permissions:
  contents: write # Wajib untuk memberikan izin menulis ke branch gh-pages (mencegah error 403)

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies 📦
        run: npm install

      - name: Build Frontend 🏗️
        run: npx vite build
        env:
          VITE_BASE_URL: '/test/' # Sesuaikan dengan nama repository Anda agar aset /assets/ ter-load dengan benar

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
